INSERT INTO tabel_mahasiswa (nim, nama_mahasiswa, jenis_kelamin, alamat, jurusan) VALUES
(125, 'Aji Prabowo', 'L', 'Jalan Raya Cibubur No. 14, Depok', 'TI'),
(126, 'Cinta Indriani', 'P', 'Jalan Kuningan No. 16, Tangerang', 'SI'),
(127, 'Dika Rahadian', 'L', 'Jalan Mangga No. 12, Bogor', 'TK'),
(128, 'Eva Kusumawati', 'P', 'Jalan Raya Sejahtera No. 20, Depok', 'TI'),
(129, 'Farhan Rizky', 'L', 'Jalan Raya Puncak No. 8, Bogor', 'SI'),
(130, 'Gina Lestari', 'P', 'Jalan Buah No. 5, Tangerang', 'TK'),
(131, 'Husni Alamsyah', 'L', 'Jalan Pahlawan No. 3, Depok', 'TI'),
(132, 'Ika Amalia', 'P', 'Jalan Bunga No. 9, Tangerang', 'SI'),
(133, 'Jaya Santoso', 'L', 'Jalan Jati No. 6, Bogor', 'TK'),
(134, 'Kiki Putri', 'P', 'Jalan Damai No. 11, Depok', 'TI'),
(135, 'Lina Ratnasari', 'P', 'Jalan Mentari No. 4, Tangerang', 'SI'),
(136, 'Mika Anindita', 'P', 'Jalan Rindang No. 7, Bogor', 'TK'),
(137, 'Niko Adi', 'L', 'Jalan Mawar No. 2, Depok', 'TI'),
(138, 'Omar Bayu', 'L', 'Jalan Rawa No. 13, Tangerang', 'SI'),
(139, 'Putri Ramadhani', 'P', 'Jalan Cendana No. 15, Bogor', 'TK'),
(140, 'Rizki Abdurrahman', 'L', 'Jalan Suka No. 18, Depok', 'TI'),
(141, 'Sari Wulandari', 'P', 'Jalan Kebon Nanas No. 21, Tangerang', 'SI'),
(142, 'Tama Perdana', 'L', 'Jalan Sejahtera No. 17, Bogor', 'TK'),
(143, 'Umi Kalsum', 'P', 'Jalan Cibubur No. 19, Depok', 'TI'),
(144, 'Vino Raharja', 'L', 'Jalan Biru No. 10, Tangerang', 'SI'),
(145, 'Wira Ananda', 'L', 'Jalan Sayang No. 24, Bogor', 'TK'),
(146, 'Yasmin Tania', 'P', 'Jalan Terang No. 22, Depok', 'TI'),
(147, 'Zara Hani', 'P', 'Jalan Mutiara No. 23, Tangerang', 'SI'),
(148, 'Anisa Pertiwi', 'P', 'Jalan Hujan No. 25, Bogor', 'TK'),
(149, 'Budi Santoso', 'L', 'Jalan Kenanga No. 26, Depok', 'TI'),
(150, 'Cahya Suryana', 'L', 'Jalan Pelangi No. 27, Tangerang', 'SI'),
(151, 'Dewi Hidayati', 'P', 'Jalan Gembira No. 28, Bogor', 'TK'),
(152, 'Eko Setiawan', 'L', 'Jalan Taman No. 29, Depok', 'TI'),
(153, 'Fahri Alamsyah', 'L', 'Jalan Puspa No. 30, Tangerang', 'SI'),
(154, 'Gita Yuliana', 'P', 'Jalan Bintang No. 31, Bogor', 'TK'),
(155, 'Hendi Prasetyo', 'L', 'Jalan Jaya No. 32, Depok', 'TI'),
(156, 'Iwan Maulana', 'L', 'Jalan Fajar No. 33, Tangerang', 'SI'),
(157, 'Jeni Sari', 'P', 'Jalan Bumi No. 34, Bogor', 'TK'),
(158, 'Kurniawan', 'L', 'Jalan Indah No. 35, Depok', 'TI'),
(159, 'Larasati', 'P', 'Jalan Harmoni No. 36, Tangerang', 'SI'),
(160, 'Milan Dhananjaya', 'L', 'Jalan Citra No. 37, Bogor', 'TK'),
(161, 'Nita Adisty', 'P', 'Jalan Tanjung No. 38, Depok', 'TI'),
(162, 'Oki Ferdiansyah', 'L', 'Jalan Suka No. 39, Tangerang', 'SI'),
(163, 'Putra Kuncoro', 'L', 'Jalan Air No. 40, Bogor', 'TK'),
(164, 'Rina Widiastuti', 'P', 'Jalan Mentari No. 41, Depok', 'TI'),
(165, 'Sandi Ahmad', 'L', 'Jalan Kembang No. 42, Tangerang', 'SI'),
(166, 'Tina Julianti', 'P', 'Jalan Sari No. 43, Bogor', 'TK'),
(167, 'Udin Slamet', 'L', 'Jalan Bahagia No. 44, Depok', 'TI'),
(168, 'Vira Melati', 'P', 'Jalan Murni No. 45, Tangerang', 'SI'),
(169, 'Wawan Kurnia', 'L', 'Jalan Pahlawan No. 46, Bogor', 'TK'),
(170, 'Yosep Mahardika', 'L', 'Jalan Palem No. 47, Depok', 'TI'),
(171, 'Zara Nayla', 'P', 'Jalan Teratai No. 48, Tangerang', 'SI'),
(172, 'Arief Aji', 'L', 'Jalan Mawar No. 49, Bogor', 'TK'),
(173, 'Bunga Permata', 'P', 'Jalan Air No. 50, Depok', 'TI'),
(174, 'Cahya Irawan', 'L', 'Jalan Cemara No. 51, Tangerang', 'SI'),
(175, 'Dinda Shafira', 'P', 'Jalan Sinar No. 52, Bogor', 'TK'),
(176, 'Eka Darmawan', 'L', 'Jalan Sejahtera No. 53, Depok', 'TI'),
(177, 'Ferry Nugraha', 'L', 'Jalan Harapan No. 54, Tangerang', 'SI'),
(178, 'Gina Safira', 'P', 'Jalan Cempaka No. 55, Bogor', 'TK'),
(179, 'Hendra Fadillah', 'L', 'Jalan Rinjani No. 56, Depok', 'TI'),
(180, 'Intan Arum', 'P', 'Jalan Kasih No. 57, Tangerang', 'SI'),
(181, 'Jaya Putra', 'L', 'Jalan Palapa No. 58, Bogor', 'TK'),
(182, 'Kiki Amelia', 'P', 'Jalan Kenangan No. 59, Depok', 'TI'),
(183, 'Lutfi Hasan', 'L', 'Jalan Terang No. 60, Tangerang', 'SI'),
(184, 'Mira Indri', 'P', 'Jalan Damai No. 61, Bogor', 'TK'),
(185, 'Nugroho', 'L', 'Jalan Cinta No. 62, Depok', 'TI'),
(186, 'Okti Jaya', 'L', 'Jalan Mulia No. 63, Tangerang', 'SI'),
(187, 'Putri Ayu', 'P', 'Jalan Mentari No. 64, Bogor', 'TK'),
(188, 'Randi Wijaya', 'L', 'Jalan Puspa No. 65, Depok', 'TI'),
(189, 'Siti Farida', 'P', 'Jalan Harapan No. 66, Tangerang', 'SI'),
(190, 'Tanto Aji', 'L', 'Jalan Jaya No. 67, Bogor', 'TK'),
(191, 'Uci Aprilia', 'P', 'Jalan Kebun No. 68, Depok', 'TI'),
(192, 'Vivi Nabila', 'P', 'Jalan Pahlawan No. 69, Tangerang', 'SI'),
(193, 'Wahyu Setiawan', 'L', 'Jalan Suka No. 70, Bogor', 'TK'),
(194, 'Yani Kusumawati', 'P', 'Jalan Sukacita No. 71, Depok', 'TI'),
(195, 'Zulfiqri', 'L', 'Jalan Harapan No. 72, Tangerang', 'SI'),
(196, 'Alva Ramadhan', 'L', 'Jalan Silang No. 73, Bogor', 'TK'),
(197, 'Bela Cinta', 'P', 'Jalan Pusat No. 74, Depok', 'TI'),
(198, 'Candra Pramono', 'L', 'Jalan Jaya No. 75, Tangerang', 'SI'),
(199, 'Dika Hendra', 'L', 'Jalan Agung No. 76, Bogor', 'TK'),
(200, 'Elisa Kirana', 'P', 'Jalan Mawar No. 77, Depok', 'TI');
